### ISSUE TITLE
Feature: errno_str(int errno)

### ISSUE THREAD

**Issue by yuandong1222** [coolceph/cceph#26]
get string description for errno.

**Comment by songbaisen** [comment]
HI? It is really a huge work to do this?How long do you want to finished it?

**Comment by yuandong1222** [comment]
I think you mean the whole project not just this issue, right?

Indeed I don't have strict schedule since I work on this project in my off hours. 

So my plan is at least one commit per day.

Maybe one year later, we can have a demo version of rados including write, read, delete and the recovery. 

Thanks for your concern. Happy Spring Festival.

**Comment by songbaisen** [comment]
I really admire of you to do this.If  change all the ceph code from c++ to C, it will be more simple to read and the speed will be more faster.But use the c++  is easy to develop the complex system.Without the stl and boost may be need to write more code.A lot of function should write by hand.But since the linux kernel  and github are all  writed by c,It is a hard work to do  but have a better  future.I will continue concern your progrem.

PI YIN：SHI YI CHANG JI YI ZHI YI。

Best with to you! Happy Spriing Festival too!
